# Generated by Django 5.2.1 on 2025-06-03 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_is_client_remove_user_is_freelancer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelanceprofile",
            name="user",
        ),
        migrations.CreateModel(
            name="FreelancerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.TextField()),
                ("experience", models.IntegerField()),
                ("bio", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ClientProfile",
        ),
        migrations.DeleteModel(
            name="FreelanceProfile",
        ),
    ]
