# Generated by Django 5.2.1 on 2025-06-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_freelanceprofile_user_freelancerprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("client", "Client"), ("freelancer", "Freelancer")],
                max_length=20,
                null=True,
            ),
        ),
    ]
