# Generated by Django 5.2.1 on 2025-06-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_clientprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientprofile",
            options={
                "permissions": [
                    ("access_client_dashboard", "Can access clien dashboard")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="freelancerprofile",
            options={
                "permissions": [
                    ("access_freelancer_dashboard", "Can access freelancer dashboard")
                ]
            },
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="website",
        ),
        migrations.RemoveField(
            model_name="freelancerprofile",
            name="bio",
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="project_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="company_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="freelancerprofile",
            name="experience",
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
