# Generated by Django 5.2.1 on 2025-06-04 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_clientprofile_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientprofile",
            options={},
        ),
        migrations.AlterModelOptions(
            name="freelancerprofile",
            options={},
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="project_description",
        ),
        migrations.RemoveField(
            model_name="freelancerprofile",
            name="experience",
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="freelancerprofile",
            name="skills",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter", models.TextField()),
                ("expected_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.jobpost",
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "freelancer")},
            },
        ),
    ]
